"""
Django settings for vde_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production! Le défaut
# est False (contrairement au défaut historique Django) : un déploiement où
# la variable d'env est oubliée doit tomber en mode strict plutôt qu'exposer
# les stack traces/requêtes SQL à n'importe quel visiteur.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret! En debug
# local, une valeur par défaut est tolérée pour ne pas bloquer le
# développement sans .env. En production (DEBUG=False), la variable d'env
# DJANGO_SECRET_KEY est obligatoire — on échoue au démarrage plutôt que de
# tourner silencieusement avec une clé connue de tous (committée dans git).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-57h-_$rna68qo^)n2!gwe&x2#ut3gtptz@g+kiv6vy1s_*wsdj'
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY doit être définie en production (DEBUG=False). "
            "Génère-en une et ajoute-la aux variables d'environnement de Render."
        )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'exploitation',
    'pointage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vde_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vde_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        # Les connexions sont gardées ouvertes 10 minutes : rouvrir une
        # connexion TLS vers Neon à chaque requête coûterait cher depuis
        # Abidjan.
        conn_max_age=600,
        # ...mais Neon ferme les connexions inactives de son côté, sans
        # prévenir. Sans cette vérification, Django ressort du réservoir une
        # connexion déjà morte et la requête casse sur un
        # « SSL connection has been closed unexpectedly » — c'est arrivé en
        # production le 08/08/2026 sur /api/sante/. Django teste désormais la
        # connexion avant de la réutiliser et en rouvre une si besoin.
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Durée de validité d'un lien « mot de passe oublié ». Le défaut de Django
# est de 3 JOURS : un lien resté dans une boîte mail reste alors exploitable
# tout ce temps. 2 heures suffisent largement pour recevoir le message et
# choisir un mot de passe, et redemander un lien ne coûte rien.
PASSWORD_RESET_TIMEOUT = 2 * 60 * 60

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Stockage des fichiers uploadés (photos de profil) sur Cloudinary quand
# configuré — indispensable en production : le disque des hébergeurs
# gratuits type Render est éphémère, un fichier stocké localement disparaît
# au premier redémarrage. En local (pas de CLOUDINARY_CLOUD_NAME), on garde
# le stockage disque classique défini ci-dessus.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
if CLOUDINARY_STORAGE['CLOUD_NAME']:
    STORAGES['default'] = {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
] + [o.strip() for o in os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Render (comme la plupart des PaaS) termine le TLS sur son proxy et transmet
# la requête en HTTP en interne — sans ce header, Django croit que toutes les
# requêtes sont en clair et ne peut pas savoir qu'il doit exiger le flag
# Secure sur les cookies de session/CSRF (utilisés par /admin/).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Render redirige déjà HTTP vers HTTPS à son niveau ; ceci est la
    # ceinture en plus des bretelles, au cas où l'appli serait un jour servie
    # ailleurs. Sans risque pour le ping anti-veille de
    # .github/workflows/keep-alive.yml, qui appelle déjà l'URL en https://.
    SECURE_SSL_REDIRECT = True

    # HSTS : indique au navigateur de ne plus JAMAIS tenter cette adresse en
    # clair pendant la durée indiquée. C'est ce qui bloque une attaque de
    # rétrogradation sur un réseau public (wifi d'hôtel, partage de connexion
    # inconnu) — un scénario réel pour Direction en déplacement.
    #
    # Attention, c'est en partie irréversible : le navigateur mémorise la
    # consigne et l'applique même si on retire le réglage du serveur. D'où la
    # montée en puissance par paliers, pilotée par variable d'environnement :
    #   1h (défaut ci-dessous) -> vérifier que tout va bien pendant quelques
    #   jours -> 86400 (1 jour) -> 31536000 (1 an) une fois serein.
    #
    # includeSubDomains et preload restent désactivés par défaut : ils
    # engagent TOUS les sous-domaines présents et futurs, et le preload est
    # quasi impossible à annuler. `check --deploy` les signalera (W005/W021) —
    # c'est un choix, pas un oubli.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_HSTS_SUBDOMAINS', 'False') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_HSTS_PRELOAD', 'False') == 'True'

# Base publique du frontend, utilisée pour générer l'URL encodée dans les QR
# codes de pointage (le backend n'a sinon aucun moyen de connaître l'adresse
# du frontend Netlify).
FRONTEND_URL = os.environ.get('DJANGO_FRONTEND_URL', 'http://localhost:5173')

# Alertes proactives (stock bas, mortalité, ponte, croissance...) envoyées
# par email via Brevo (relais SMTP, gratuit jusqu'à 300 emails/jour) — cf.
# management command exploitation/verifier_alertes et conversation du
# 26/07/2026 avec Serge. En local (pas de clé Brevo), les emails partent
# simplement dans la console au lieu d'échouer.
BREVO_SMTP_LOGIN = os.environ.get('BREVO_SMTP_LOGIN', '')
BREVO_SMTP_KEY = os.environ.get('BREVO_SMTP_KEY', '')
if BREVO_SMTP_LOGIN and BREVO_SMTP_KEY:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'smtp-relay.brevo.com')
    # 2525 et non 587 : Render filtre le port SMTP habituel (06/08/2026,
    # mesuré — l'envoi restait bloqué sans jamais échouer, jusqu'au délai).
    # Brevo écoute sur 2525 précisément pour ce cas. La valeur par défaut est
    # celle qui marche en production, pour que la panne ne revienne pas si la
    # variable d'environnement venait à disparaître.
    EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '2525'))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = BREVO_SMTP_LOGIN
    EMAIL_HOST_PASSWORD = BREVO_SMTP_KEY
    # Sans ce délai, Django attend Brevo sans limite. Comme l'envoi se fait
    # pendant la requête HTTP, c'est l'utilisateur qui attend : le 06/08/2026,
    # une demande de réinitialisation est restée bloquée 30 s, Render a coupé,
    # et le navigateur a affiché « Serveur injoignable » — alors que le
    # serveur, lui, allait très bien. Mieux vaut renoncer vite : la panne est
    # journalisée, et la réponse reste la même de toute façon.
    EMAIL_TIMEOUT = int(os.environ.get('DJANGO_EMAIL_TIMEOUT', '10'))
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'alertes@volailles-de-lest.local')
# Django utilise SERVER_EMAIL (pas DEFAULT_FROM_EMAIL) comme expéditeur des
# emails d'erreur — sans ça, l'expéditeur par défaut est root@localhost, que
# Brevo refuse (adresse non vérifiée).
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ALERTES_EMAILS_DESTINATAIRES = [e.strip() for e in os.environ.get('DJANGO_ALERTES_EMAILS', '').split(',') if e.strip()]

# Suivi d'erreurs en production, sans dépendre d'un service tiers (Sentry
# alourdirait le bundle frontend, à contre-courant du travail de
# code-splitting fait pour les zones à réseau faible) : réutilise l'email déjà
# configuré (Brevo). Une exception serveur non gérée (ADMINS + LOGGING
# Django par défaut) ET une erreur JS non interceptée côté client (logguée
# via /api/erreurs-frontend/, cf. exploitation.views.signaler_erreur_frontend)
# déclenchent toutes les deux un email à ADMINS — cf. conversation du
# 30/07/2026 avec Serge : "aucun suivi d'erreurs en production".
ADMINS = [(e.strip(), e.strip()) for e in os.environ.get('DJANGO_ADMINS_EMAILS', '').split(',') if e.strip()]
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            # Sous-classe qui écrit sur stderr quand l'envoi échoue : celui de
            # Django avale l'échec, ce qui a rendu ce suivi d'erreurs
            # totalement inopérant et invisible du 30/07 au 07/08/2026.
            'class': 'vde_backend.journalisation.HandlerEmailAdminBavard',
        },
        # Une erreur JS n'a pas besoin du rapport d'exception du serveur :
        # il décrit la mauvaise machine et enterre l'information utile.
        'mail_erreur_frontend': {
            'level': 'ERROR',
            'class': 'vde_backend.journalisation.HandlerErreurFrontend',
        },
    },
    'loggers': {
        'vde.frontend_errors': {
            'handlers': ['mail_erreur_frontend'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

REST_FRAMEWORK = {
    # TokenAuthentication en premier : DRF n'utilise que le PREMIER
    # authentificateur de cette liste pour décider s'il annonce un en-tête
    # WWW-Authenticate. SessionAuthentication n'en fournit pas, donc tant
    # qu'elle était en tête, DRF dégradait tous les échecs d'authentification
    # en 403 — indiscernables d'un vrai refus d'autorisation. Le frontend ne
    # pouvait donc pas distinguer « ton jeton n'est plus valable, reconnecte-
    # toi » de « tu n'as pas le droit d'ouvrir cette page », et un
    # intercepteur générique aurait déconnecté un technicien qui touche
    # simplement un écran réservé à la Direction. Avec Token en tête :
    # 401 = jeton absent/invalide, 403 = authentifié mais pas autorisé.
    # L'ordre ne change rien à l'authentification elle-même — les deux
    # classes restent essayées, /admin/ continue d'utiliser la session.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Limite le bruteforce sur le login/2FA (cf. exploitation/deux_facteurs.py) :
    # sans ça, rien n'empêchait un script de tenter des mots de passe ou des
    # codes TOTP à 6 chiffres en boucle.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'connexion': '10/min',
        # Endpoints publics du pointage (scan, badges de secours/absence,
        # activation d'appareil) — aucun compte à vérifier, donc une limite
        # par IP est le seul garde-fou contre un script qui les martèle.
        # Généreux pour l'usage réel (un seul téléphone partagé scanne les
        # employés un par un, plusieurs secondes par selfie).
        'pointage_public': '60/min',
        'erreurs_frontend': '20/min',
    },
}
