# Generated by Django 6.0.7 on 2026-07-25 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitation', '0008_magasin_stock_aliment_initial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('taux_horaire', models.DecimalField(decimal_places=2, help_text='FCFA par heure travaillée', max_digits=10)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='exploitation.ferme')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.DateTimeField(blank=True, null=True)),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_du_jour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='pointage.employe')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employe', 'date'), name='un_pointage_par_employe_et_par_jour')],
            },
        ),
    ]
