# Generated by Django 6.0.7 on 2026-07-26 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optionnel — si cette personne a aussi un compte de connexion (chef/sous-chef/superviseur).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_pointage', to=settings.AUTH_USER_MODEL),
        ),
    ]
