# Generated by Django 6.0.7 on 2026-07-26 12:12

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_salaire_mensuel(apps, schema_editor):
    """Reconstitue salaire_mensuel à partir de l'ancien taux_horaire saisi à
    la main, pour ne pas silencieusement remettre à 0 le salaire d'un
    employé existant à sa prochaine sauvegarde (taux_horaire devient
    calculé automatiquement à partir de ce moment)."""
    Employe = apps.get_model("pointage", "Employe")
    JOURS_OUVRABLES_MOIS = 26
    HEURES_JOUR_STANDARD = Decimal("10.5")
    for employe in Employe.objects.all():
        employe.salaire_mensuel = (employe.taux_horaire * JOURS_OUVRABLES_MOIS * HEURES_JOUR_STANDARD).quantize(Decimal("0.01"))
        employe.save(update_fields=["salaire_mensuel"])


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_employe_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='jour_repos',
            field=models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de repos hebdomadaire de cet employé', null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FCFA par mois', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé automatiquement : salaire_mensuel / (26 jours × 10,5 h)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optionnel — si cette personne a aussi un compte de connexion (chef/sous-chef/superviseur/ouvrier/gardien).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_pointage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='pointage.employe')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employe', 'date'), name='une_absence_par_employe_et_par_jour')],
            },
        ),
        migrations.RunPython(backfill_salaire_mensuel, migrations.RunPython.noop),
    ]
