# Generated by Django 6.0.7 on 2026-07-26 15:09

from django.db import migrations, models


def backfill_fermes(apps, schema_editor):
    """Reporte l'ancienne ferme unique de chaque employé dans la nouvelle
    relation plusieurs-à-plusieurs, avant de supprimer l'ancien champ —
    aucun employé existant ne doit perdre sa ferme."""
    Employe = apps.get_model("pointage", "Employe")
    for employe in Employe.objects.all():
        employe.fermes.add(employe.ferme_id)


class Migration(migrations.Migration):

    dependencies = [
        ('exploitation', '0009_alter_profilutilisateur_role'),
        ('pointage', '0003_employe_jour_repos_employe_salaire_mensuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fermes',
            field=models.ManyToManyField(help_text='Plusieurs fermes possibles (ex: un superviseur qui en supervise plusieurs).', related_name='employes', to='exploitation.ferme'),
        ),
        migrations.RunPython(backfill_fermes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employe',
            name='ferme',
        ),
    ]
