# Generated by Django 6.0.7 on 2026-07-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_remove_employe_ferme_employe_fermes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LignePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois concerné (ex: 2026-06-01 pour juin 2026)')),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carburant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appel_internet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(blank=True, choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Money'), ('MOOV_MONEY', 'Moov Money'), ('ESPECES', 'Main en main'), ('VIREMENT', 'Virement bancaire')], max_length=15)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PAYE', 'Payé')], default='A_PAYER', max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_paie', to='pointage.employe')),
            ],
            options={
                'ordering': ['-mois'],
                'constraints': [models.UniqueConstraint(fields=('employe', 'mois'), name='une_ligne_paie_par_employe_et_par_mois')],
            },
        ),
    ]
