# Generated by Django 6.0.7 on 2026-07-26 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_lignepaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
