# Generated by Django 6.0.7 on 2026-07-26 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_badgetemporaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée (payée)'), ('REJETEE', 'Rejetée (non payée)')], default='VALIDEE', max_length=10),
        ),
    ]
