# Generated by Django 6.0.7 on 2026-07-27 11:58

import django.db.models.deletion
import pointage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_badgeabsence_absence_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('CONTRAT', 'Contrat de travail'), ('AUTRE', 'Autre document')], default='AUTRE', max_length=10)),
                ('nom', models.CharField(blank=True, help_text='Libellé libre (ex: « CNI recto », « Contrat 2026 »)', max_length=150)),
                ('fichier', models.FileField(storage=pointage.models._storage_documents_employes, upload_to='documents_employes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pointage.employe')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
