# Generated by Django 6.0.7 on 2026-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0008_documentemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='photo_debut',
            field=models.ImageField(blank=True, null=True, upload_to='pointages_selfies/'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='photo_fin',
            field=models.ImageField(blank=True, null=True, upload_to='pointages_selfies/'),
        ),
    ]
