# Generated by Django 6.0.7 on 2026-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0010_appareilpointage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='arrivee_via_secours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointage',
            name='depart_via_secours',
            field=models.BooleanField(default=False),
        ),
    ]
