# Generated by Django 6.0.7 on 2026-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0011_pointage_arrivee_via_secours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareilpointage',
            name='derniere_utilisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
