# Generated by Django 6.0.7 on 2026-08-06 09:57

import exploitation.stockage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0013_evaluationemploye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=exploitation.stockage.stockage_images_privees, upload_to='employes/'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='photo_debut',
            field=models.ImageField(blank=True, null=True, storage=exploitation.stockage.stockage_images_privees, upload_to='pointages_selfies/'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='photo_fin',
            field=models.ImageField(blank=True, null=True, storage=exploitation.stockage.stockage_images_privees, upload_to='pointages_selfies/'),
        ),
    ]
