# Generated by Django 6.0.7 on 2026-08-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0014_alter_employe_photo_alter_pointage_photo_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='latitude_debut',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='latitude_fin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='longitude_debut',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='longitude_fin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='sans_position_debut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointage',
            name='sans_position_fin',
            field=models.BooleanField(default=False),
        ),
    ]
